function candidateHardCount(temp,placed,cid){const g=group(temp.groupId),t=teacher(temp.teacherId),r=room(temp.roomId);let n=0;if(!g||!t||!canTeach(t,g,temp.subjectId))n+=20;if(t){const spec=teacherLoadSpec(t,cid);if(teacherAssignedIn(placed,t.id)+(temp.duration||1)>Number(spec.max))n+=20;if(rule('teacherDailyMax').hard){for(const w of temp.weeks||lessonWeeks(temp,cid)){const dn=placed.filter(x=>x.teacherId===t.id&&x.day===temp.day&&lessonWeeks(x,cid).includes(w)).reduce((a,x)=>a+(x.duration||1),0)+(temp.duration||1);if(dn>Number(spec.dailyMax||4)){n+=10;break}}}}if(!r||r.type!==g?.roomType||r.capacity<(g?.students||999))n+=20;if(Math.max(...occupied(temp))>maxPeriod())n+=20;occupied(temp).forEach(p=>{if(rule('timeBlocked').hard&&isBlockedByTime(temp,cid,temp.day,p))n+=10;if(r?.blocked[roomBlockKey(cid,temp.day,p)])n+=10});placed.filter(x=>overlapTime(temp,x)&&lessonsOverlapWeeks(temp,x,cid)).forEach(x=>{const gx=group(x.groupId);if(x.teacherId===temp.teacherId)n+=20;if(x.roomId===temp.roomId)n+=20;if(overlapsClasses(g,gx)&&!sameSync(g,gx))n+=20});if(rule('buildingTravel').hard){placed.filter(x=>x.day===temp.day&&lessonsOverlapWeeks(temp,x,cid)).forEach(x=>{const gx=group(x.groupId);if((x.teacherId===temp.teacherId||(overlapsClasses(g,gx)&&!sameSync(g,gx)))&&adjacentTravelIssue(temp,x,cid))n+=20})}groupClasses(g).forEach(c=>{for(const w of temp.weeks||lessonWeeks(temp,cid)){const set=classWeekDaySet(c.id,cid,temp.day,w,[...placed,temp]);if(rule('classDailyMax').hard&&set.size>c.dailyMax)n+=10}});return n}
function candidateScore(temp,placed,cid){let s=-candidateHardCount(temp,placed,cid)*1000;occupied(temp).forEach(p=>s+=preferredCount(temp,cid,temp.day,p)*rule('teacherPreferred').weight*8);const g=group(temp.groupId),rq=requirement(temp.reqId),sub=subject(temp.subjectId);if(sub?.core)s-=(temp.period-1)*rule('coreEarly').weight*2;if(rq?.preferredRoomIds?.includes(temp.roomId))s+=rule('roomPreference').weight*8;if(rq?.alternativeRoomIds?.includes(temp.roomId))s+=rule('roomPreference').weight*2;groupClasses(g).forEach(c=>{for(const w of temp.weeks||reqWeeks(rq,cid)){const before=classWeekDaySet(c.id,cid,temp.day,w,placed),after=classWeekDaySet(c.id,cid,temp.day,w,[...placed,temp]);s+=(gapCount(before)-gapCount(after))*rule('classNoGaps').weight*10}});const prev=previousCycle(cid);if(prev){const old=(state.schedules[prev.id]||[]).find(x=>x.reqId===temp.reqId&&x.blockIndex===temp.blockIndex);if(old&&old.day===temp.day&&old.period===temp.period)s+=rule('previousCycle').weight*10}const sameDay=placed.filter(x=>x.reqId===temp.reqId&&x.day===temp.day).length;s-=sameDay*rule('spreadSubject').weight*7;return s}

function roughUnitDomain(u,cid,locked=[]){let slots=0;for(const d of DAYS)for(const p of periodNums()){if(u.blocks.some(b=>p+b.duration-1>maxPeriod()))continue;let ok=true;const usedT=new Set(),usedR=new Set();for(const b of u.blocks){const g=group(b.groupId),ts=availableTeachers(g,b.subjectId).filter(t=>!usedT.has(t.id)),rs=eligibleRooms(g,requirement(b.reqId)).filter(r=>!usedR.has(r.id));if(!ts.length||!rs.length){ok=false;break}const anyT=ts.some(t=>!occupied({...b,day:d,period:p}).some(pp=>effectiveEntityTime('teacher',t.id,cid,d,pp)==='blocked'));if(!anyT){ok=false;break}usedT.add(ts[0].id);usedR.add(rs[0].id)}if(ok)slots++}return slots}
function chooseTeachersForUnit(u,cid,placed,reqTeacher,rng){const chosen={},used=new Set();for(const b of u.blocks){if(reqTeacher[b.reqId]){chosen[b.reqId]=reqTeacher[b.reqId];if(u.syncKey)used.add(reqTeacher[b.reqId]);continue}const g=group(b.groupId),cand=availableTeachers(g,b.subjectId).filter(t=>!used.has(t.id)).filter(t=>teacherAssignedIn(placed,t.id)+b.duration<=teacherLoadSpec(t,cid).max);cand.sort((a,b2)=>teacherAssignedIn(placed,a.id)/Math.max(1,teacherLoadSpec(a,cid).target)-teacherAssignedIn(placed,b2.id)/Math.max(1,teacherLoadSpec(b2,cid).target)+(rng()-.5)*.25);if(!cand.length)return null;chosen[b.reqId]=cand[0].id;reqTeacher[b.reqId]=cand[0].id;if(u.syncKey)used.add(cand[0].id)}return chosen}
function teacherAssignedIn(arr,tid){return arr.filter(l=>l.teacherId===tid).reduce((a,l)=>a+(l.duration||1),0)}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function buildAttempt(cid,seed){const rng=mulberry32(seed),existing=deep(schedule(cid)),locked=existing.filter(l=>l.locked),placed=deep(locked),next=deep(locked),reqTeacher={};locked.filter(l=>l.teacherId).forEach(l=>reqTeacher[l.reqId]??=l.teacherId);let units=demandUnits(cid);units.sort((a,b)=>roughUnitDomain(a,cid,locked)-roughUnitDomain(b,cid,locked)||b.blocks.length-a.blocks.length||rng()-.5);
  for(const u of units){const lockedBlocks=u.blocks.map(b=>locked.find(l=>l.reqId===b.reqId&&l.blockIndex===b.blockIndex)).filter(Boolean);if(lockedBlocks.length){for(const b of u.blocks){if(!lockedBlocks.some(l=>l.reqId===b.reqId&&l.blockIndex===b.blockIndex)){const old=existing.find(l=>l.reqId===b.reqId&&l.blockIndex===b.blockIndex);if(old){old.locked=false;next.push(old);placed.push(old)}}}continue}const tids=chooseTeachersForUnit(u,cid,placed,reqTeacher,rng);if(!tids)continue;let best=null,bestScore=-Infinity;const candidates=[];for(const d of DAYS)for(const p of periodNums()){if(u.blocks.some(b=>p+b.duration-1>maxPeriod()))continue;const temps=[],usedRooms=new Set();let total=0,ok=true;for(const b of u.blocks){const g=group(b.groupId),rq=requirement(b.reqId),rs=eligibleRooms(g,rq).filter(r=>!usedRooms.has(r.id));let br=null,bs=-Infinity;for(const rr of rs){const tmp={id:uid('l'),cycleId:cid,reqId:b.reqId,groupId:b.groupId,subjectId:b.subjectId,teacherId:tids[b.reqId],roomId:rr.id,day:d,period:p,duration:b.duration,blockIndex:b.blockIndex,locked:false,weeks:b.weeks};const sc=candidateScore(tmp,[...placed,...temps],cid);if(sc>bs){bs=sc;br=tmp}}if(!br||candidateHardCount(br,[...placed,...temps],cid)>0){ok=false;break}usedRooms.add(br.roomId);temps.push(br);total+=bs}if(ok)candidates.push({temps,total:total+rng()})}candidates.sort((a,b)=>b.total-a.total);const pick=candidates[Math.min(candidates.length-1,Math.floor(rng()*Math.min(3,candidates.length)))];if(pick){pick.temps.forEach(l=>{next.push(l);placed.push(l)})}}
  return next}
function optimize(cid,depth='better'){const attempts=depth==='quick'?6:depth==='deep'?80:24;snapshot('Optimeerimine');let best=null,bestMetric=Infinity;for(let i=0;i<attempts;i++){const arr=buildAttempt(cid,Date.now()%100000+i*977);const sc=scoreSchedule(cid,arr),missing=missingBlocks(cid,arr).length,metric=sc.hard*1e7+missing*1e5+sc.penalty;if(metric<bestMetric){bestMetric=metric;best=arr}}state.schedules[cid]=best||schedule(cid);save();renderAll();toast(`Optimeerimine valmis · ${attempts} varianti`)}
function missingBlocks(cid,arr=schedule(cid)){const have=new Set(arr.map(l=>l.reqId+'|'+l.blockIndex));return demandUnits(cid).flatMap(u=>u.blocks.filter(b=>!have.has(b.reqId+'|'+b.blockIndex)).map(b=>({unit:u,block:b})))}
function coverage(r,cid,arr=schedule(cid)){const need=reqHours(r,cid),got=arr.filter(l=>l.reqId===r.id).reduce((a,l)=>a+(l.duration||1),0);return{need,got}}

function targetEvaluation(l,cid,day,period){const targets=syncTargets(l,cid),placed=schedule(cid).filter(x=>!targets.some(t=>t.id===x.id));let hard=0,score=0;for(const x of targets){const t={...x,day,period,weeks:lessonWeeks(x,cid)};hard+=candidateHardCount(t,placed,cid);score+=candidateScore(t,placed,cid);placed.push(t)}if(hard>0)return'impossible';if(score>40)return'best';if(score>0)return'good';return'bad'}
function syncTargets(l,cid){const g=group(l.groupId);return g?.syncKey?schedule(cid).filter(x=>group(x.groupId)?.syncKey===g.syncKey&&x.blockIndex===l.blockIndex):[l]}
function moveLesson(l,cid,day,period){const targets=syncTargets(l,cid);if(targets.some(x=>x.locked))return toast('Paralleelpaketis on lukustatud tund');const quality=targetEvaluation(l,cid,day,period);if(quality==='impossible')return toast('See sihtkoht rikub kõva piirangut');commit('Tunni liigutamine',()=>targets.forEach(x=>{x.day=day;x.period=period}))}
function moveRoom(l,cid,roomId){if(l.locked)return toast('Tund on lukus');const g=group(l.groupId),r=room(roomId);if(!r||r.type!==g.roomType||r.capacity<g.students)return toast('Ruum ei sobi');commit('Ruumi muutmine',()=>l.roomId=roomId)}
function toggleLock(l,cid){const targets=syncTargets(l,cid),v=!targets.every(x=>x.locked);commit(v?'Tunni lukustamine':'Tunni vabastamine',()=>targets.forEach(x=>x.locked=v))}
function replaceTeacher(l,cid){const g=group(l.groupId),cand=availableTeachers(g,l.subjectId);const ans=prompt(cand.map((t,i)=>`${i+1}. ${t.name}`).join('\n'),String(Math.max(1,cand.findIndex(t=>t.id===l.teacherId)+1)));const t=cand[Number(ans)-1];if(t)commit('Õpetaja vahetamine',()=>syncTargets(l,cid).filter(x=>x.reqId===l.reqId).forEach(x=>x.teacherId=t.id))}

function entityOptions(type){if(type==='teacher')return state.teachers.map(x=>({id:x.id,name:x.name}));if(type==='class')return state.classes.map(x=>({id:x.id,name:x.name}));if(type==='group')return state.groups.map(x=>({id:x.id,name:x.name}));if(type==='subject')return state.subjects.map(x=>({id:x.id,name:x.name}));if(type==='room')return state.rooms.map(x=>({id:x.id,name:x.name}));return state.requirements.map(x=>({id:x.id,name:`${group(x.groupId)?.name||'?'} · ${subject(x.subjectId)?.name||'?'}`}))}
function setOptions(el,items,value=x=>x.id,label=x=>x.name,empty){if(!el)return;const old=el.value;el.innerHTML=(empty!==undefined?`<option value="">${empty}</option>`:'')+items.map(x=>`<option value="${value(x)}">${label(x)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old}
function showPage(name){activePage=name;$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='diagnostics')renderDiagnostics();if(name==='builder')renderBuilder()}

