const days=['Esmaspäev','Teisipäev','Kolmapäev','Neljapäev','Reede'], periods=[1,2,3,4,5,6], classes=['7A','7B','8A','8B'], subjects=['Matemaatika','Eesti keel','Ajalugu','Füüsika','Informaatika','Inglise keel'];
const key=(d,p)=>d+'|'+p;
let rooms={
 '204':{type:'tavaklass',blocked:{}},'112':{type:'tavaklass',blocked:{'Kolmapäev|6':1}},'305':{type:'tavaklass',blocked:{}},'206':{type:'tavaklass',blocked:{'Reede|1':1}},'Lab 1':{type:'labor',blocked:{'Esmaspäev|1':1,'Esmaspäev|2':1}},'Arvuti 1':{type:'arvutiklass',blocked:{'Reede|6':1}}
};
let teachers={
 Mari:{contactHours:14,maxDaily:4,availability:{'Teisipäev|1':'preferred','Teisipäev|2':'preferred','Teisipäev|3':'preferred','Kolmapäev|1':'blocked','Kolmapäev|2':'blocked','Kolmapäev|3':'blocked','Kolmapäev|4':'blocked','Kolmapäev|5':'blocked','Kolmapäev|6':'blocked'},skills:[['Matemaatika','7A'],['Matemaatika','7B'],['Matemaatika','8A'],['Matemaatika','8B'],['Informaatika','7A']]},
 Jüri:{contactHours:9,maxDaily:3,availability:{'Neljapäev|1':'preferred','Neljapäev|2':'preferred','Neljapäev|3':'preferred','Neljapäev|4':'preferred','Reede|1':'blocked','Reede|2':'blocked'},skills:[['Ajalugu','7A'],['Ajalugu','7B'],['Ajalugu','8A'],['Ajalugu','8B'],['Inglise keel','7A']]},
 Katrin:{contactHours:13,maxDaily:4,availability:{'Esmaspäev|1':'blocked','Kolmapäev|4':'preferred','Kolmapäev|5':'preferred','Kolmapäev|6':'preferred'},skills:[['Eesti keel','7A'],['Eesti keel','7B'],['Eesti keel','8A'],['Eesti keel','8B'],['Inglise keel','7B'],['Inglise keel','8A']]},
 Andres:{contactHours:12,maxDaily:3,availability:{'Esmaspäev|1':'blocked','Esmaspäev|2':'blocked','Teisipäev|4':'preferred','Teisipäev|5':'preferred'},skills:[['Füüsika','7A'],['Füüsika','7B'],['Füüsika','8A'],['Füüsika','8B'],['Informaatika','7A'],['Informaatika','7B'],['Informaatika','8A'],['Informaatika','8B']]}
};
let requirements=[]; classes.forEach(c=>[['Matemaatika',3,'tavaklass'],['Eesti keel',3,'tavaklass'],['Ajalugu',2,'tavaklass'],['Füüsika',2,'labor'],['Informaatika',1,'arvutiklass']].forEach(([s,h,r])=>requirements.push({id:c+'-'+s,className:c,subject:s,weeklyHours:h,roomType:r})));
let lessons=[], availabilityDraft={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function fill(el,arr,empty){el.innerHTML=(empty!==undefined?`<option value="">${empty}</option>`:'')+arr.map(x=>`<option>${x}</option>`).join('')}
function canTeach(t,s,c){return teachers[t]?.skills.some(x=>x[0]===s&&x[1]===c)}
function roomList(type){return Object.keys(rooms).filter(r=>rooms[r].type===type)}
function assigned(t){return lessons.filter(l=>l.teacher===t).length}
function build(preserve=true){const old=preserve?structuredClone(lessons):[];let n=1,next=[];requirements.forEach(r=>{for(let i=0;i<r.weeklyHours;i++){let x=old.find(l=>l.reqId===r.id&&l.instance===i);next.push(x?{...x,subject:r.subject,className:r.className,roomType:r.roomType}:{id:n++,reqId:r.id,instance:i,subject:r.subject,className:r.className,roomType:r.roomType,teacher:null,room:null,day:null,period:null,locked:false})}});lessons=next}
function seed(){build(false);[['7A','Matemaatika','Mari','204','Esmaspäev',2],['7A','Eesti keel','Katrin','112','Esmaspäev',3],['7A','Ajalugu','Jüri','305','Teisipäev',1],['7A','Füüsika','Andres','Lab 1','Kolmapäev',2],['7B','Matemaatika','Mari','204','Neljapäev',3],['7B','Eesti keel','Katrin','112','Kolmapäev',4],['8A','Ajalugu','Jüri','305','Neljapäev',4],['8A','Informaatika','Andres','Arvuti 1','Teisipäev',5],['8B','Matemaatika','Mari','204','Esmaspäev',4],['8B','Füüsika','Andres','Lab 1','Neljapäev',5]].forEach(a=>{let l=lessons.find(x=>x.className===a[0]&&x.subject===a[1]&&!x.teacher);if(l)Object.assign(l,{teacher:a[2],room:a[3],day:a[4],period:a[5]})})}
function hard(l){let a=[];if(!l.teacher)a.push('õpetaja määramata');if(!l.day)a.push('aeg määramata');if(l.teacher&&!canTeach(l.teacher,l.subject,l.className))a.push('puudub pädevus');if(l.teacher&&l.day&&teachers[l.teacher].availability[key(l.day,l.period)]==='blocked')a.push('õpetaja keelatud aeg');if(l.room&&rooms[l.room]?.type!==l.roomType)a.push('vale ruumitüüp');if(l.room&&rooms[l.room]?.blocked[key(l.day,l.period)])a.push('ruum blokeeritud');if(l.day){let peers=lessons.filter(x=>x.id!==l.id&&x.day===l.day&&x.period===l.period);if(peers.some(x=>x.className===l.className))a.push('klass topelt');if(l.teacher&&peers.some(x=>x.teacher===l.teacher))a.push('õpetaja topelt');if(l.room&&peers.some(x=>x.room===l.room))a.push('ruum topelt');let d=lessons.filter(x=>x.teacher===l.teacher&&x.day===l.day).length;if(l.teacher&&d>teachers[l.teacher].maxDaily)a.push('päevane maksimum')}if(l.teacher&&assigned(l.teacher)>teachers[l.teacher].contactHours)a.push('kontakttunnid ületatud');return [...new Set(a)]}
function soft(l){return l.teacher&&l.day&&teachers[l.teacher].availability[key(l.day,l.period)]==='preferred'?[]:(l.teacher&&l.day?['mitte-eelistatud aeg']:[])}
function coverage(r){let c=lessons.filter(l=>l.reqId===r.id&&l.teacher&&l.day&&!hard(l).length).length;return [c,r.weeklyHours]}
function renderAvailability(){let e=$('#teacherAvailabilityGrid');e.innerHTML='<div class="avail-head"></div>'+days.map(d=>`<div class="avail-head">${d.slice(0,3)}</div>`).join('');periods.forEach(p=>{e.innerHTML+=`<div class="avail-period">${p}</div>`;days.forEach(d=>{let s=availabilityDraft[key(d,p)]||'free';e.innerHTML+=`<button class="avail-cell ${s==='free'?'':s}" data-av="${d}|${p}">${s==='preferred'?'eelistatud':s==='blocked'?'keelatud':'vaba'}</button>`})});$$('[data-av]').forEach(b=>b.onclick=()=>{let [d,p]=b.dataset.av.split('|'),k=key(d,p),s=availabilityDraft[k]||'free',n=s==='free'?'preferred':s==='preferred'?'blocked':'free';if(n==='free')delete availabilityDraft[k];else availabilityDraft[k]=n;renderAvailability()})}
function skillRow(s=subjects[0],c=classes[0]){let d=document.createElement('div');d.className='skill-row';d.innerHTML=`<select class="skillSubject">${subjects.map(x=>`<option ${x===s?'selected':''}>${x}</option>`).join('')}</select><select class="skillClass">${classes.map(x=>`<option ${x===c?'selected':''}>${x}</option>`).join('')}</select><button class="dangerBtn">×</button>`;d.querySelector('button').onclick=()=>d.remove();$('#skillList').appendChild(d)}
function loadTeacher(){let t=teachers[$('#teacherSelect').value];$('#contactHours').value=t.contactHours;$('#maxDaily').value=t.maxDaily;availabilityDraft=structuredClone(t.availability||{});$('#skillList').innerHTML='';t.skills.forEach(x=>skillRow(x[0],x[1]));renderAvailability()}
function saveTeacher(){let name=$('#teacherSelect').value,t=teachers[name];t.contactHours=+$ ('#contactHours').value;t.maxDaily=+$ ('#maxDaily').value;t.availability=structuredClone(availabilityDraft);t.skills=$$('.skill-row').map(r=>[r.querySelector('.skillSubject').value,r.querySelector('.skillClass').value]);note(`${name} salvestatud.`,'ok');render()}
function renderReq(){let e=$('#requirementList');e.innerHTML=requirements.map(r=>`<div class="req-row"><div><strong>${r.className}</strong><div class="mini">${r.subject}</div></div><div class="mini">${r.roomType}</div><div class="mini"><b>${r.weeklyHours}</b> t/n</div><button class="dangerBtn" data-r="${r.id}">×</button></div>`).join('');$$('[data-r]').forEach(b=>b.onclick=()=>{requirements=requirements.filter(r=>r.id!==b.dataset.r);build();render()})}
function visible(){let f=$('#viewFilter').value,a=lessons.filter(l=>l.day);if(f==='all')return a;if(f.startsWith('class:'))return a.filter(l=>l.className===f.split(':')[1]);return a.filter(l=>l.teacher===f.split(':')[1])}
function lessonCard(l,roomMode=false){let h=hard(l),s=soft(l),d=document.createElement('div');d.className='lesson'+(l.locked?' locked':'')+(h.length?' conflict':(!h.length&&s.length?' softconflict':''));d.draggable=!l.locked;d.dataset.id=l.id;d.innerHTML=`<strong>${l.subject} · ${l.className}</strong><span>${l.teacher||'õpetaja?'} · ${l.room||'ruum?'}</span>${l.locked?'<span class="lock">🔒</span>':''}`;d.title=[...h,...s].join('\n');d.onclick=()=>{l.locked=!l.locked;render()};d.ondragstart=e=>e.dataTransfer.setData('text/plain',l.id);return d}
function renderSchedule(){let tb=$('#schedule tbody');tb.innerHTML='';periods.forEach(p=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${p}</td>`;days.forEach(day=>{let td=document.createElement('td');td.className='slot';visible().filter(l=>l.day===day&&l.period===p).forEach(l=>td.appendChild(lessonCard(l)));if(!td.children.length)td.innerHTML='<div class="empty">vaba</div>';td.ondragover=e=>e.preventDefault();td.ondrop=e=>{e.preventDefault();let l=lessons.find(x=>x.id==e.dataTransfer.getData('text/plain'));if(l&&!l.locked){l.day=day;l.period=p;if(!l.room)l.room=roomList(l.roomType)[0];render()}};tr.appendChild(td)});tb.appendChild(tr)})}
function renderRooms(){let day=$('#roomDay').value,tb=$('#roomLanes tbody');tb.innerHTML='';Object.entries(rooms).forEach(([room,r])=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${room}<span class="room-info">${r.type}</span></td>`;periods.forEach(p=>{let td=document.createElement('td'),blocked=r.blocked[key(day,p)];td.className='room-slot'+(blocked?' room-blocked':'');let b=document.createElement('button');b.className='room-lock-btn'+(blocked?' blocked':'');b.textContent=blocked?'🔒':'🔓';b.onclick=e=>{e.stopPropagation();if(blocked)delete r.blocked[key(day,p)];else r.blocked[key(day,p)]=1;render()};td.appendChild(b);lessons.filter(l=>l.room===room&&l.day===day&&l.period===p).forEach(l=>td.appendChild(lessonCard(l,true)));td.ondragover=e=>e.preventDefault();td.ondrop=e=>{e.preventDefault();let l=lessons.find(x=>x.id==e.dataTransfer.getData('text/plain'));if(l&&!l.locked){l.room=room;l.day=day;l.period=p;render()}};tr.appendChild(td)});tb.appendChild(tr)})}
function renderDash(){let cb=$('#classCoverageBody');cb.innerHTML=requirements.map(r=>{let [c,n]=coverage(r),ok=c===n;return `<tr><td>${r.className}</td><td>${r.subject}</td><td>${c}/${n}</td><td class="${ok?'coverage-ok':c?'coverage-warn':'coverage-bad'}">${ok?'Kaetud':n-c+' puudu'}</td></tr>`}).join('');let tb=$('#teacherCapacityBody');tb.innerHTML=Object.entries(teachers).map(([n,t])=>{let a=assigned(n),f=t.contactHours-a,p=t.contactHours?Math.min(100,a/t.contactHours*100):0;return `<tr><td>${n}</td><td>${a}/${t.contactHours}</td><td class="${f<0?'coverage-bad':''}">${f}</td><td><div class="bar ${f<0?'over':''}"><i style="width:${p}%"></i></div></td></tr>`}).join('');$('#kpiRequired').textContent=requirements.reduce((a,r)=>a+r.weeklyHours,0);$('#kpiScheduled').textContent=lessons.filter(l=>l.teacher&&l.day).length;$('#kpiUncovered').textContent=requirements.reduce((a,r)=>{let [c,n]=coverage(r);return a+Math.max(0,n-c)},0);$('#kpiFreeCapacity').textContent=Object.keys(teachers).reduce((a,t)=>a+Math.max(0,teachers[t].contactHours-assigned(t)),0)}
function renderTeacherSummary(){$('#teacherSummary').innerHTML=Object.entries(teachers).map(([n,t])=>{let a=assigned(n),f=t.contactHours-a;return `<div class="teacher-summary ${f<0?'bad':''}"><div class="section-title"><strong>${n}</strong><span class="mini">${a}/${t.contactHours} · vaba ${f}</span></div><div class="mini">${t.skills.slice(0,4).map(x=>x.join(' ')).join(', ')}</div></div>`}).join('')}
function renderStats(){let hs=lessons.flatMap(l=>hard(l).map(x=>`${l.className} ${l.subject}: ${x}`)),ss=lessons.flatMap(l=>soft(l));$('#hardBadge').textContent=hs.length+' kõva';$('#softBadge').textContent=ss.length+' pehmet';$('#score').textContent=Math.max(0,100-hs.length*4-ss.length)+'%';$('#conflictList').innerHTML=hs.slice(0,10).map(x=>`<div class="conflict-item">🟥 ${x}</div>`).join('')||'<div class="conflict-item">✅ Kõvasid konflikte pole</div>'}
function renderUnplaced(){let a=lessons.filter(l=>!l.teacher||!l.day);$('#unplacedPool').innerHTML=a.length?a.map(l=>`<span class="chip warn">${l.className} · ${l.subject}</span>`).join(''):'<span class="chip">Kõik tunnid paigutatud.</span>'}
function render(){renderSchedule();renderRooms();renderDash();renderTeacherSummary();renderStats();renderUnplaced();renderReq()}
function note(t,type='ok'){$('#notice').className='notice show '+type;$('#notice').textContent=t}
function optimize(){let counts=Object.fromEntries(Object.keys(teachers).map(t=>[t,0]));lessons.forEach(l=>{if(l.locked&&l.teacher)counts[l.teacher]++});lessons.filter(l=>!l.locked).forEach(l=>{if(!l.teacher||!canTeach(l.teacher,l.subject,l.className)||counts[l.teacher]>=teachers[l.teacher].contactHours){let c=Object.keys(teachers).filter(t=>canTeach(t,l.subject,l.className)&&counts[t]<teachers[t].contactHours).sort((a,b)=>counts[a]-counts[b]);l.teacher=c[0]||null}if(l.teacher)counts[l.teacher]++});let placed=lessons.filter(l=>l.locked&&l.day);lessons.filter(l=>!l.locked).forEach(l=>{if(!l.teacher){l.day=l.period=l.room=null;return}let best=null,score=-1e9;for(let d of days)for(let p of periods)for(let r of roomList(l.roomType)){let test={...l,day:d,period:p,room:r},h=hardCandidate(test,placed),s=teachers[l.teacher].availability[key(d,p)]==='preferred'?8:0,v=-h*100+s+Math.random();if(v>score){score=v;best=[d,p,r]}}if(best&&score>-100){[l.day,l.period,l.room]=best;placed.push(l)}else{l.day=l.period=l.room=null}});note('Uus variant arvutatud.','ok');render()}
function hardCandidate(l,placed){let n=0;if(teachers[l.teacher].availability[key(l.day,l.period)]==='blocked')n++;if(rooms[l.room].blocked[key(l.day,l.period)])n++;let peers=placed.filter(x=>x.day===l.day&&x.period===l.period);if(peers.some(x=>x.teacher===l.teacher))n++;if(peers.some(x=>x.className===l.className))n++;if(peers.some(x=>x.room===l.room))n++;return n}
fill($('#teacherSelect'),Object.keys(teachers));fill($('#reqClass'),classes);fill($('#reqSubject'),subjects);fill($('#roomDay'),days);$('#viewFilter').innerHTML='<option value="all">Kõik tunnid</option>'+classes.map(c=>`<option value="class:${c}">Klass ${c}</option>`).join('')+Object.keys(teachers).map(t=>`<option value="teacher:${t}">Õpetaja ${t}</option>`).join('');
$('#teacherSelect').onchange=loadTeacher;$('#addSkillBtn').onclick=()=>skillRow();$('#saveTeacherBtn').onclick=saveTeacher;$('#addRequirementBtn').onclick=()=>{let c=$('#reqClass').value,s=$('#reqSubject').value,h=+$('#reqHours').value,rt=$('#reqRoomType').value,r=requirements.find(x=>x.className===c&&x.subject===s);if(r){r.weeklyHours=h;r.roomType=rt}else requirements.push({id:Date.now()+'',className:c,subject:s,weeklyHours:h,roomType:rt});build();render()};$('#checkBtn').onclick=()=>{renderStats();note('Kontroll tehtud.','ok')};$('#optimizeBtn').onclick=optimize;$('#resetBtn').onclick=()=>location.reload();$('#viewFilter').onchange=render;$('#roomDay').onchange=renderRooms;$$('[data-main-view]').forEach(b=>b.onclick=()=>{$$('[data-main-view]').forEach(x=>x.classList.toggle('active',x===b));$('#scheduleView').classList.toggle('hidden',b.dataset.mainView!=='schedule');$('#roomsView').classList.toggle('hidden',b.dataset.mainView!=='rooms');});
seed();loadTeacher();render();